//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enabled_Subjects
    {
        public Nullable<int> ID_Пользователя { get; set; }
        public Nullable<int> ID_Группы { get; set; }
        public Nullable<int> ID_Предмета { get; set; }
        public int ID { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Users Users { get; set; }
    }
}
