//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sys.Windows
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skips
    {
        public int ID_Записи { get; set; }
        public Nullable<int> ID_Студента { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> ID_Пользователя { get; set; }
        public Nullable<int> ID_Предмета { get; set; }
        public Nullable<int> Номер_пары { get; set; }
        public string Комментарий { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Users Users { get; set; }
    }
}
